name: Release

on:
  push:
    tags:
      - "v*"

env:
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    if: ${{ false }}
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: Build Image
        run: |
          make build
      - name: Tag Image
        run: make tag-image
      - name: Authenticate Image Registry
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - name: Push Image
        run: make push-image

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: install cargo
        run: curl https://sh.rustup.rs -y -sSf | sh
      - name: install targets
        run: |
          rustup target add x86_64-pc-windows-gnu # building on linux for windows
          rustup target add x86_64-apple-darwin # building on linux for Mac OS X
      - name: build
        run: |
          cargo build --release
          cd target/release
          mv clone-git-subdirectory cgs
          cd ../..
          cargo build --release --target=x86_64-pc-windows-gnu
          cd target/release
          mv clone-git-subdirectory cgs-windows
          cd ../..
          cargo build --release --target=x86_64-apple-darwin
          cd target/release
          mv clone-git-subdirectory cgs-mac
      - name: rename build executable to cgs
        run: |
          cd target/release
          mv clone-git-subdirectory cgs
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          target/release/cgs
          target/release/cgs-mac
          target/release/cgs-windows
